server:
    port: 15041
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: 1234
    application:
        name:  SpringBootTwoRabbit
    mail:
       host: smtp.qiye.163.com //邮箱服务器地址
       username: xxx@oo.com //用户名
       password: xxyyooo    //密码
       default-encoding: UTF-8
mail:
    fromMail:
        addr: xxx@oo.com  //以谁来发送邮件